# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cddcba875e570933233fd581acbd2f6045401e4b50c59b5e2016e7f589e8868a9cde4f82ac6afef2caa60fc7ae7af7cdab93e77fb4d3ca2ec5e879bce28a740

test:
  secret_key_base: df1cd5f6f447d2ef94a826ca447e64154c7958675316b896c312bda1e6412af03ba8cac47677ed1b3220f23b52c8704b7defc6edbc007e06ab412580397f488a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
