# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2601168c4564938c73cb561415dcd9b1b2940739b2934006956dd6e1a755059b23bf478ae10fba5789301726a0692d664fed91720a281af4b1b9f4c6c8ef619

test:
  secret_key_base: 7e5482551212d23ad56e64748200d493ed049815e15d8a0a4bc38738e6ca9e90c4b4a8bd346e9687ce7fcc181a91cd80e059ead0e59db4bdd2217e42143f6a34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
